### ISSUE TITLE
Using CUDA version 10.1

### ISSUE THREAD

**Issue by ksanjeevan** [aws/sagemaker-pytorch-container#116]
I'm having some compatibility issues when using `pytorch-1.1.0` and cuda 9. What should I include in the Dockerfile in order to use 10.1?

Thanks.

**Comment by ChuyangDeng** [comment]
Hi @ksanjeevan, thank you for using SageMaker! Our GPU image uses pytorch 1.1 with cuda 10.1 runtime, as shown here: https://github.com/aws/sagemaker-pytorch-container/blob/master/docker/1.1.0/base/Dockerfile.gpu#L1

**Comment by ksanjeevan** [comment]
Yeah I found that the other day! Yet when I print `torch.version.cuda` on my `entry_point.py` file I get:

```bash
algo-1-0lcg9_1  | /usr/bin/python -m entry_point --gpu 1
algo-1-0lcg9_1  | 
algo-1-0lcg9_1  | 
algo-1-0lcg9_1  | CUDA version: 9.0.176
algo-1-0lcg9_1  | Epoch: 0
algo-1-0lcg9_1  | 2019-07-02 20:47:56,107 sagemaker-containers ERROR    ExecuteUserScriptError:
algo-1-0lcg9_1  | Command "/usr/bin/python -m entry_point --gpu 1"
algo-1-0lcg9_1  | THCudaCheck FAIL file=/pytorch/aten/src/THC/THCGeneral.cpp line=383 error=11 : invalid argument
```
Any thoughts on what could be causing this? Perhaps I have some package not up to date? This is causing an error like the one displayed above when using new `torchvision` models.

**Comment by ChuyangDeng** [comment]
Hi @ksanjeevan, it seems like there's no support for CUDA 10.1 from PyTorch, and to avoid breaking changes, our image does `pip install torch==1.1.0` instead of building from source.

I found an article that might be useful for you to install CUDA 10 for PyTorch: https://medium.com/@zhanwenchen/install-cuda-10-1-and-cudnn-7-5-0-for-pytorch-on-ubuntu-18-04-lts-9b6124c44cc

**Comment by ksanjeevan** [comment]
Hmmm ok, just to confirm @ChuyangDeng: despite https://github.com/aws/sagemaker-pytorch-container/blob/master/docker/1.1.0/base/Dockerfile.gpu#L1 the Pytorch 1.1.0 image will install cuda 9 right? And for now cuda 10 won't be an option so my best bet is to create a custom image that installs cuda 10.1?

Thanks!

**Comment by ksanjeevan** [comment]
Ok so I figured out that the pytorch 1.1.0 docker image does in fact use CUDA 10.1, but the pytorch install is CUDA 9. By simply including a pip install of `cu100/torch` in the Dockerfile all works as expected.
