### ISSUE TITLE
PyTorch: increasing --shm-size to allow multiprocessing data loaders

### ISSUE THREAD

**Issue by ksanjeevan** [aws/sagemaker-pytorch-container#117]
As explained [here](https://github.com/pytorch/pytorch#docker-image), the default shared memory for docker is quite low. `--shm-size` seems to be the solution found online (preferable to --ipc=host`) but in any case these are args passed to `docker run` and can not be set on build (?). 

What options do we have through SageMaker to configure this? Running training with `num_workers=0` makes training way slower... For that matter, is there any way to set args we want to pass to `docker run`?

Thanks.

**Comment by ChuyangDeng** [comment]
Hi @ksanjeevan, thanks for using SageMaker! Our default build command does not have `--shm-size` arg. But if you want to configure this variable, you can use our pre-built PyTorch image and extend from it to customize your container.

Here's an example of [Extending our PyTorch containers](https://github.com/awslabs/amazon-sagemaker-examples/blob/master/advanced_functionality/pytorch_extending_our_containers/pytorch_extending_our_containers.ipynb)

**Comment by ksanjeevan** [comment]
@ChuyangDeng but `--shm-size` can't be configured in the Dockerfile so extending the image won't work. This is a runtime argument so has to be passed to `docker run`.

**Comment by ChuyangDeng** [comment]
Hi @ksanjeevan, I was not clear in the previous reply. The our default command to run the container does not have `--shm-size` option provided. So if you want to do this, you will have to run your own container and train with it.

**Comment by faustomilletari** [comment]
I suppose this is still an issue that could be easily resolved by sagemaker. if sagemaker runs kubernetes in the back, it should not be difficult to just run the jobs with more shm memory or ipc=host

**Comment by sonunitjsr223** [comment]
@faustomilletari could you please elaborate more on your suggestion. How can I use Kubernetes in sagemaker to configure the shm size?
