### ISSUE TITLE
Pytorch 1.2

### ISSUE THREAD

**Issue by radcheb** [aws/sagemaker-pytorch-container#132]
Pytorch 1.2 dockerfile is provided in this repo but it's not built (not available in ECR):

520713654638.dkr.ecr.eu-west-1.amazonaws.com/sagemaker-pytorch:1.2.0-cpu-py3 not found.

**Comment by mvsusp** [comment]
Hi @radcheb ,

You can find the ECR repo of the PyTorch 1.2 container in the SageMaker documentation https://docs.aws.amazon.com/sagemaker/latest/dg/pre-built-containers-frameworks-deep-learning.html

Thanks for using SageMaker.

**Comment by ralphma-insitro** [comment]
The documentation only has documentation about PyTorch 1.1 and not 1.2.

Getting `The image '520713654638.dkr.ecr.us-west-2.amazonaws.com/sagemaker-pytorch:1.2.0-cpu-py3' does not exist..`

**Comment by radcheb** [comment]
@mvsusp The image still does not exist in ECR.

**Comment by ajaykarpur** [comment]
Hi @radcheb and @ralphma-insitro, sorry for the confusion. I believe the image will be available in ECR within the next day or two.

**Comment by ajaykarpur** [comment]
@radcheb and @ralphma-insitro, the PyTorch 1.2 image should now be available. Please let us know if you have any other questions.

**Comment by ruijianw** [comment]
HI @ajaykarpur , it is not available on `us-east-1`, could you take a look?
```
Step 2/10 : FROM 520713654638.dkr.ecr.$REGION.amazonaws.com/sagemaker-pytorch:1.2.0-cpu-py3
manifest for 520713654638.dkr.ecr.us-east-1.amazonaws.com/sagemaker-pytorch:1.2.0-cpu-py3 not found: manifest unknown: Requested image not found```

**Comment by laurenyu** [comment]
@ruijianw starting with PyTorch 1.2, the image URIs now follow the format `763104351884.dkr.ecr.<region>.amazonaws.com/pytorch-training:1.2.0-<cpu|gpu>-py3`

for more, see https://docs.aws.amazon.com/sagemaker/latest/dg/pre-built-containers-frameworks-deep-learning.html

**Comment by ruijianw** [comment]
@laurenyu Thanks for the reply.

A follow up question, what is the difference between `pytorch-training` and `pytorch-inference`?

I am trying to bring some model outside of SageMaker, but failed on `pytorch-inference` and `pytorch-training`. But it works on `sagemaker-pytorch:1.1.0-cpu-py3`.


I guess I may need to open another issue for this.

**Comment by laurenyu** [comment]
@ruijianw `pytorch-training` is for training and hyperparameter tuning; `pytorch-inference` is for deploying to endpoints and batch transform jobs.
