### ISSUE TITLE
Pytorch 1.3 ?

### ISSUE THREAD

**Issue by cedias** [aws/sagemaker-pytorch-container#137]
Hi,
The 1.3 version of pytorch (https://github.com/pytorch/pytorch/releases) have been released and I was wondering if you were planning to add support ?

Thanks

**Comment by laurenyu** [comment]
Thank you for your interest! I've reached out to the corresponding team for their input.

**Comment by anankira** [comment]
Thank you for your interest ! Yes, we plan to add support for Pytorch 1.3. However, we currently do not have a timeline to share.

**Comment by ruodingt** [comment]
It would be really nice to have the support for pytorch1.3

**Comment by akartsky** [comment]
Pytorch 1.3.1 containers are released.
Docker files will be merged to this repo in a few days.

**Comment by domino14** [comment]
Hi @akartsky and others. Does AWS update their pre-built Docker images frequently? I am still using this line in my Dockerfile:

```FROM 520713654638.dkr.ecr.us-east-1.amazonaws.com/sagemaker-pytorch:1.1.0-gpu-py3```

Replacing `1.1.0` with anything above does not work - those images don't seem to exist.

**Comment by laurenyu** [comment]
versions 1.2.0+ follow a different format:

```763104351884.dkr.ecr.us-east-1.amazonaws.com/pytorch-training:1.3.1-gpu-py3```

https://docs.aws.amazon.com/sagemaker/latest/dg/pre-built-containers-frameworks-deep-learning.html

**Comment by siavashdarkvision** [comment]
@laurenyu where is a list of these magic repositories? The link that you mention does not list them.

**Comment by laurenyu** [comment]
@siavashdarkvision looks like the page has been updated, but it does link to: https://github.com/aws/deep-learning-containers/blob/master/available_images.md

**Comment by siavashdarkvision** [comment]
@laurenyu if I extend a recent version of `pytorch-training` image like 1.7.1 using [this](https://github.com/aws/amazon-sagemaker-examples/blob/master/advanced_functionality/pytorch_extending_our_containers/pytorch_extending_our_containers.ipynb), will I be able to do hyper-parameter tuning?

**Comment by laurenyu** [comment]
@siavashdarkvision it should work!

(if you run into problems, please open a new issue since hyperparameter tuning is a separate topic and this issue has been closed for over a year)
