### ISSUE TITLE
unable to build

### ISSUE THREAD

**Issue by richardbedwell-imaginecurve** [aws/sagemaker-pytorch-container#141]
I am unable to build an image with the dockerfile in this repo (specifically i am using the cpu version).

running the command

`docker build -t sagemaker-inference-images .`

ends at:

`Step 20/29 : COPY lib/changehostname.c /
COPY failed: stat /var/lib/docker/tmp/docker-builder354479123/lib/changehostname.c: no such file or directory`

**Comment by saimidu** [comment]
Hi @richardbedwell-imaginecurve,

Thank you for raising this issue. I believe the issue arises from the fact that the intended build context for dockerfiles in this repository is the base directory for the repo.

The base directory contains a directory named [lib](https://github.com/aws/sagemaker-pytorch-container/tree/master/lib), with the [changehostname.c](https://github.com/aws/sagemaker-pytorch-container/blob/master/lib/changehostname.c) file inside.

I believe running a command with the following template, once you have cloned the repository and entered its directory, should allow you to build successfully:

```
docker build -t <image_name>:<tag> -f docker/<PyTorch_version>/<Python_version>/Dockerfile.cpu .
```

For example, to build a CPU Py3 image for PyTorch 1.2.0 using the dockerfile at [docker/1.2.0/py3/Dockerfile.cpu](https://github.com/aws/sagemaker-pytorch-container/blob/master/docker/1.2.0/py3/Dockerfile.cpu):

```
docker build -t preprod-pytorch:1.2.0-cpu-py3 -f docker/1.2.0/py3/Dockerfile.cpu  .
```

Could you please try this out and respond with the outcome?

**Comment by domino14** [comment]
Hi @saimidu, I'm not the OP but I tried to build the GPU version and it fails at step 36.

```Step 36/40 : COPY dist/sagemaker_pytorch_container-1.2-py2.py3-none-any.whl /sagemaker_pytorch_container-1.2-py2.py3-none-any.whl
COPY failed: stat /var/lib/docker/tmp/docker-builder203823212/dist/sagemaker_pytorch_container-1.2-py2.py3-none-any.whl: no such file or directory```

My build command was:

`docker build -t pytorch-base:1.2.0-gpu-py3 -f docker/1.2.0/py3/Dockerfile.gpu  .`

**Comment by domino14** [comment]
I was able to build it by doing this:

```cd sagemaker-pytorch-container
python setup.py bdist_wheel```

**Comment by saimidu** [comment]
Hi @domino14, Yes, that is the correct prerequisite step to be taken before the docker build is started. The build requires the `sagemaker_pytorch_container-1.2-py2.py3-none-any.whl` to be available in the `dist/` directory in the build context.
