### ISSUE TITLE
ModuleNotFoundError: No module named 'sagemaker_pytorch_container.serving'

### ISSUE THREAD

**Issue by derlin** [aws/sagemaker-pytorch-container#144]
I built both the pytorch-1.2.0-gpu-py3 and pytorch-1.1.0-gpu-py3 images and tried to deploy a model in local mode using `PytorchModel`. I always get the error:

> ModuleNotFoundError: No module named 'sagemaker_pytorch_container.serving'

Which makes sense, since when looking both inside the docker image and inside the [src/sagemaker_pytorch_container](https://github.com/aws/sagemaker-pytorch-container/tree/master/src/sagemaker_pytorch_container), I don't see any `serving.py` script, only `training.py`.

Did I miss something ? How can I build a pytorch image able to do both training and serving from this repo ?

**Comment by nadiaya** [comment]
Pytorch hosting functionality was separated into a different container. Please use https://github.com/aws/sagemaker-pytorch-serving-container for serving/hosting.
