### ISSUE TITLE
container for fastai2

### ISSUE THREAD

**Issue by gloriamacia** [aws/sagemaker-pytorch-container#151]
Fastai v2 is already out with the course starting pretty soon. I would like to run the examples on Sagemaker. My feature request would be to have a container for it. 
Currently, the docker code is as follows: 

```
`# The following section uninstalls torch and torchvision before installing the
# custom versions from an S3 bucket. This will need to be removed in the future
RUN pip install \
    --no-cache-dir smdebug==0.5.0.post0 \
    sagemaker-experiments==0.1.3 \
    --no-cache-dir fastai==1.0.59 \
 && pip install --no-cache-dir -U https://pytorch-aws.s3.amazonaws.com/pytorch-1.3.1/py3/gpu/torch-1.3.1-cp36-cp36m-manylinux1_x86_64.whl \
 && pip uninstall -y torchvision \
 && pip install --no-cache-dir -U \
    https://torchvision-build.s3.amazonaws.com/1.3.1/gpu/torchvision-0.4.2-cp36-cp36m-linux_x86_64.whl`
```

I installed fastai v2 in colab easily with the following lines. 

`pip install -q torch torchvision feather-format kornia pyarrow Pillow==6.2.1 wandb nbdev fastprogress --upgrade 
pip install -q git+https://github.com/fastai/fastcore  --upgrade
pip install -q git+https://github.com/fastai/fastai2  
`
would the same work for AWS? Not sure why you are pulling torch and torchvision from s3.

**Comment by surajkota** [comment]
Hi @gloriamacia 

Yes you can build your own container with the dependencies you need and use it on Sagemaker. You will need to use the pytorch related binaries hosted on S3 if you wish to use [Sagemaker Debugger](https://docs.aws.amazon.com/sagemaker/latest/dg/train-debugger.html)

If you do not want to use Sagemaker debugger, you can use the preinstalled torch and only install/upgrade set of the packages needed to run fastai or choose to install pytorch from pipy.

Thanks
