### ISSUE TITLE
requirements.txt not working

### ISSUE THREAD

**Issue by hrsma2i** [aws/sagemaker-pytorch-container#189]
My training job fails with the following error:

```
ModuleNotFoundError: No module named 'ignite'
```

I wrote `pytorch-ignite==0.3.0` in `src/requirements.txt` in my project.

The directory composition of my project is:

```
.
├── exec_train_job.py
└── src
    ├── requirements.txt
    └── train.py
```

I executed the job via `exec_train_job.py` using [aws/sagemaker-python-sdk](https://github.com/aws/sagemaker-python-sdk)'s PyTorch Estimator with the following arguments:

```py
framework_version=1.4.0
source_dir="src"
entry_point="train.py"
```

I executed it from the current directory (`.`)

```
$ python exec_train_job.py
```

The cause of the failure may be not recognizing the `requirements.txt` although it is under the same directory with the entry point (`src` including `train.py`).
The CloudWatch log shows:

```
sagemaker-containers INFO     Installing module with the following command:
/opt/conda/bin/python -m pip install . 
```

I saw [aws/sagemaker-containers/src/sagemaker_containers/_modules.py](https://github.com/aws/sagemaker-containers/blob/1d2c04e2cb728d307bf52a60d1a6da0df0e74f0a/src/sagemaker_containers/_modules.py) and know that `requirements.txt` is used when it exists in `/opt/ml/code`(=`source_dir`) 

I also checked that `s3://{default backet}/{job name}/source/sourcedir.tar.gz` includes the `requirements.txt`, indicating that the `requirements.txt` has been transferred into `opt/ml/code`.

**Comment by laurenyu** [comment]
this is a known issue with the PyTorch 1.4 training images: https://github.com/aws/sagemaker-python-sdk/issues/1371

while we wait on the fixed images to be released, there are a few workarounds, including:
1. downgrade to PyTorch 1.3.1
1. add a `subprocess.check_call(['pip', 'install', '-r', 'requirements.txt'])` to your training script

sorry for the inconvenience, and we hope to get the fix released soon

**Comment by hrsma2i** [comment]
@laurenyu 
Thank you. Sorry for the duplicated issue.

I can execute my script via `wrapper.py` as the entry point including `subprocess.check_call(['pip', 'install', '-r', 'requirements'])` without downgrading the version of PyTorch (==1.4).
