### ISSUE TITLE
Pytorch 1.5 build issue

### ISSUE THREAD

**Issue by dwang-sflscientific** [aws/sagemaker-pytorch-container#207]
Step 29/43 : COPY changehostname.c /
COPY failed: stat /var/lib/docker/tmp/docker-builder982420481/changehostname.c: no such file or directory

where's `changehostname.c`?  Didn't see it in root folder?

**Comment by dwang-sflscientific** [comment]
copy the files in `./docker/build_artifact` to root dir solved the problem.

**Comment by laurenyu** [comment]
sorry about the outdated docs. we're in the process of migrating the Dockerfiles to https://github.com/aws/deep-learning-containers, which has up-to-date instructions on building the images
