### ISSUE TITLE
PyTorch 0.4.1?

### ISSUE THREAD

**Issue by adrixcorp** [aws/sagemaker-pytorch-container#47]
Sagemaker notebooks are using PyTorch 0.4.1 in their anaconda environment but when I try to move into training and specify `framework_version='0.4.1'` in my pytorch estimator there does not appear to be a default image hosted on aws (using 0.4.0 works however). As there were a number of bug fixes in 0.4.1 is there plans to update the container to 0.4.1 any time soon?

**Comment by iquintero** [comment]
Hi @adrixcorp 

Sorry for the late reply. We don't have 0.4.1 in our plans at the moment but are constantly re-evaluating our backlog based on customer requests. 

In the meantime you can also build a 0.4.1 container yourself and use it through the python_sdk, Just specify image_name='your.dkr.ecr.amazon.com:your-custom-image:1.0' or however your image is called.

you can edit: https://github.com/aws/sagemaker-pytorch-container/blob/master/docker/0.4.0/base/Dockerfile.cpu

and replace the binaries there with 0.4.1

Im going to close this issue but feel free to re-open if you need further assistance :)
