### ISSUE TITLE
fastai libraries have different versions between cpu and gpu images

### ISSUE THREAD

**Issue by mattmcclean** [aws/sagemaker-pytorch-container#83]
Any specific reason why the GPU based Docker image is pinned to the fastai library 1.0.39 and the CPU image has the latest version (currently 1.0.49)? Means exporting models is challenging if using the GPU image for training and CPU image for inference. Would be good to have the latest version for the GPU image as well

**Comment by icywang86rui** [comment]
The pr to pin fastai to version 1.0.39 in the CPU dockerfile is merged. New containers will be released later today -
https://github.com/aws/sagemaker-pytorch-container/pull/85

Closing the issue. Feel free to reopen if you have any further question.
