### ISSUE TITLE
Python versions different in this repo's build vs SageMaker official Pytorch image

### ISSUE THREAD

**Issue by plynch-chewy** [aws/sagemaker-pytorch-container#89]
When using a `sagemaker.pytorch.PyTorch` estimator with the default image, the Python version is `3.5.2`. I also tried using the specific image `520713654638.dkr.ecr.us-east-1.amazonaws.com/sagemaker-pytorch:1.0.0.dev-gpu-py3` which also uses `3.5.2`.

The Dockerfiles in this repo use 3.6. Is the official Sagemaker image out of date? Maybe this issue belongs on the Python sdk repo?

**Comment by jesterhazy** [comment]
Our current images do use python 3.6. The docker images with 'dev' in the name are quite old pre-release images. For the current pytorch image, you should be using  `520713654638.dkr.ecr.us-east-1.amazonaws.com/sagemaker-pytorch:1.0.0-gpu-py3` (without the `dev`).

The sagemaker.pytorch.Estimator should  be selecting the same image, if you specify the `framework_version=1.0` (or 1.0.0) argument in the estimator constructor. If you don't specify a framework_version, you'll get the pytorch 0.4.0 image, which is still python 3.5.2 (and will remain so).

**Comment by plynch-chewy** [comment]
That explains it, I still had `framework_version='1.0.0.dev'` from implementing shortly after the release. Thanks for the help!
