### ISSUE TITLE
fastai latest version(1.0.51) pin

### ISSUE THREAD

**Issue by amitmukh** [aws/sagemaker-pytorch-container#90]
Hi Team,

Right now fastai has version# 1.0.51, Also all the latest fastai docs based on the latest release. Is there any timeline we can have fastai version pinned with pytorch container? Right now in Pytorch container it has 1.0.39, it would be helpful if you can upgrade the latest version with this container.

**Comment by ChuyangDeng** [comment]
Hi, thank you for using SageMaker. Can we know what is the use case that you want to use fastai version 1.0.51? And what do you need in #1.0.51 that 1.0.39 does not have?

Thanks!

**Comment by amitmukh** [comment]
Hi Team,

with 1.0.39 version the entry point script for model_fn has extra code like below:

def model_fn(model_dir):
    logger.info('model_fn')
    path = Path(model_dir)
    print('Creating DataBunch object')
    empty_data = ImageDataBunch.load_empty(path)
    arch_name = os.path.splitext(os.path.split(glob.glob(f'{model_dir}/resnet*.pth')[0])[1])[0]
    print(f'Model architecture is: {arch_name}')
    arch = getattr(models, arch_name)    
    learn = create_cnn(empty_data, arch, pretrained=False).load(path/f'{arch_name}')
    return learn

However with latest version( or atleast 1.0.48) it has less code and documentation in fastai course reffer the latest version. Also in the fastai site it was mention the same code which worked for latest version not for the 1.0.39 version.

# loads the model into memory from disk and returns it
def model_fn(model_dir):
    logger.info('model_fn')
    path = Path(model_dir)
    learn = load_learner(model_dir, fname='resnet50.pkl')
    return learn

**Comment by laurenyu** [comment]
thanks for the clarification. Unfortunately, I can't give a specific ETA for when we'll upgrade the fastai version, but we're always reprioritizing our backlog based on customer feedback.

**Comment by amitmukh** [comment]
Thanks Lauren!. Will wait for the latest fastai version pin

**Comment by gradjitta** [comment]
I had a similar requirement so the way I made it work is by building my own container
``` Dockerfile
ARG REGION=eu-west-1
ARG ARCH=gpu

# SageMaker PyTorch image
FROM 520713654638.dkr.ecr.$REGION.amazonaws.com/sagemaker-pytorch:1.0.0-$ARCH-py3

RUN python -m pip --no-cache-dir install --upgrade fastai==1.0.48
ENV LANG C.UTF-8
ENV LC_ALL C.UTF-8
```
Hope this works for you. I also got the above `Dockerfile` from [here](https://github.com/aws-samples/amazon-sagemaker-container-with-fastai/blob/master/Dockerfile)

**Comment by amitmukh** [comment]
Thanks for pinning 1.0.59 version of fastai. Please close this feature request.

**Comment by amitmukh** [comment]
Thanks for pinning 1.0.59 version of fastai. Please close this feature request.
